New approach

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -2,105 +2,142 @@
 
 source $OPENSHIFT_CARTRIDGE_SDK_BASH
 
+version=${OPENSHIFT_VERTX_VERSION}
+
 export JAVA_HOME=$OPENSHIFT_VERTX_DIR/java
 export PATH=$JAVA_HOME/bin:$PATH
 
 export LOG="$OPENSHIFT_VERTX_LOG_DIR"out.log
-export RUNNING_PID=$OPENSHIFT_REPO_DIR/RUNNING_PID
+VERTX_PID_FILE=${OPENSHIFT_HOMEDIR}/app-root/runtime/vertx.pid
 
-mkdir -p ${OPENSHIFT_VERTX_LOG_DIR}
-
-# Check whether the application is running.
-# The check is pretty simple: open a running pid file and check that the process
-# is alive.
+# Check if the vertx process is running
 function isrunning() {
   # Check for running app
-  if [ -f "$RUNNING_PID" ]; then
-    proc=$(cat $RUNNING_PID);
-    if /bin/ps --pid $proc 1>&2 >/dev/null;
+  if [ -f "$VERTX_PID_FILE" ]; then
+    vertxpid=$(cat $VERTX_PID_FILE);
+    if /bin/ps --pid $vertxpid 1>&2 >/dev/null;
     then
       return 0
     fi
   fi
+
   return 1
 }
 
-function start {
+# Kill the process given by $1 and its children
+killtree() {
+    local _pid=$1
+    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
+        killtree ${_child}
+    done
+
+    local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
+    if [ -z $should_be_gone_pid ]; then
+        return
+    else
+        kill -TERM ${_pid}
+    fi
+
+    local count=0
+    while [ ${count} -lt 15 ]
+    do
+        local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
+        if [ -z $should_be_gone_pid ]; then
+                return
+        else
+                sleep 2
+                let count=${count}+1
+        fi
+    done
+
+    local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
+    if [ ! -z $should_be_gone_pid ]
+    then
+        kill -9 ${_pid}
+    fi
+}
+
+function stop() {
+  echo "Stopping Vert.x cartridge"
+
+  if isrunning; then
+    if [ -f "$VERTX_PID_FILE" ]; then
+      pid=$(cat $VERTX_PID_FILE);
+      echo "Sending SIGTERM to vertx:$pid ..." 1>&2
+      killtree $pid
+    else
+      echo "Failed to locate Vert.x PID File" 1>&2
+    fi
+  fi
+}
+
+function setup_hazelcast {
+  # TODO: Figure out a better way to do this
+  if [ -f "$OPENSHIFT_VERTX_DIR/versions/shared/conf/cluster.xml" ]; then
+    cp $OPENSHIFT_VERTX_DIR/versions/shared/conf/cluster.xml $OPENSHIFT_VERTX_DIR/conf/
+  fi
+
+  if [ -f "$OPENSHIFT_VERTX_DIR/versions/$version/conf/cluster.xml" ]; then
+    cp $OPENSHIFT_VERTX_DIR/versions/$version/conf/cluster.xml $OPENSHIFT_VERTX_DIR/conf/
+  fi
+
+  if [ -z "$OPENSHIFT_VERTX_HAZELCAST_CLUSTER" ]; then
+    OPENSHIFT_VERTX_HAZELCAST_CLUSTER="${OPENSHIFT_VERTX_IP}:${OPENSHIFT_VERTX_HAZELCAST_PORT}"
+  fi
+
+  OPENSHIFT_VERTX_PROXY_IP=$(ping -c 1 ${OPENSHIFT_GEAR_DNS} | awk '{ print $3 ; exit }' | sed 's/(//g' | sed 's/)//g')
+
+  pushd $OPENSHIFT_VERTX_DIR > /dev/null
+      sed -i  -e "s/\${env.OPENSHIFT_VERTX_HAZELCAST_PROXY_PORT}/${OPENSHIFT_VERTX_HAZELCAST_PROXY_PORT}/g" \
+              -e "s/\${env.OPENSHIFT_VERTX_HAZELCAST_PORT}/${OPENSHIFT_VERTX_HAZELCAST_PORT}/g" \
+              -e "s/\${env.OPENSHIFT_VERTX_PROXY_IP}/${OPENSHIFT_VERTX_PROXY_IP}/g" \
+              -e "s/\${env.OPENSHIFT_VERTX_IP}/${OPENSHIFT_VERTX_IP}/g" \
+              -e "s/\${env.OPENSHIFT_VERTX_HAZELCAST_CLUSTER}/${OPENSHIFT_VERTX_HAZELCAST_CLUSTER}/g" \
+              ./conf/cluster.xml
+  popd > /dev/null
+}
+
+function start() {
   if isrunning; then
       echo "Vert.x is already running"
       return 0
   fi
 
-  echo "Starting Vert.x application"
+  echo "Starting Vert.x cartridge"
 
-  # Load configuration if any
   envf="$OPENSHIFT_REPO_DIR/configuration/vertx.env"
+  #  Source environment if it exists.
   [ -f "$envf" ]  &&  source "$envf"
 
-  export VERTX_OPTS
-
-  # Setup ports and addresses
-  VERTX_OPTS="$VERTX_OPTS -Dhttp.port=$OPENSHIFT_VERTX_PORT -Dhttp.address=$OPENSHIFT_VERTX_IP -Dhttps.port=$OPENSHIFT_VERTX_SSL_PORT -Dhttps.address=$OPENSHIFT_VERTX_SSL_IP"
-
   # Setup clustering
-  vertx_cluster=""
-  client_message "Configuring Hazelcast : ${OPENSHIFT_VERTX_HAZELCAST_PROXY_PORT}"
-      client_message "Configuring Hazelcast"
-    # setup_hazelcast
-        OPENSHIFT_VERTX_PROXY_IP=$(ping -c 1 ${OPENSHIFT_GEAR_DNS} | awk '{ print $3 ; exit }' | sed 's/(//g' | sed 's/)//g')
+  if [ "$OPENSHIFT_VERTX_HAZELCAST_PROXY_PORT" ]; then
+    setup_hazelcast
 
-        if [ -z ${OPENSHIFT_VERTX_CLUSTER_PROXY_PORT:-} ]; then
-          OPENSHIFT_VERTX_CLUSTER_PROXY_PORT=7600
-        fi
+    VERTX_OPTS="$VERTX_OPTS -Dvertx.cluster.public.host=${OPENSHIFT_VERTX_PROXY_IP} -Dvertx.cluster.public.port=${OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}"
 
-        if [ -z ${OPENSHIFT_VERTX_HAZELCAST_CLUSTER:-} ]; then
-          OPENSHIFT_VERTX_HAZELCAST_CLUSTER="${OPENSHIFT_VERTX_IP}:${OPENSHIFT_VERTX_HAZELCAST_PORT}"
-        fi
-
-        VERTX_OPTS="$VERTX_OPTS -Dvertx.cluster.public.host=${OPENSHIFT_VERTX_PROXY_IP} -Dvertx.cluster.public.port=${OPENSHIFT_VERTX_CLUSTER_PROXY_PORT}"
-
-        vertx_cluster="-cluster -cluster-port $OPENSHIFT_VERTX_CLUSTER_PORT -cluster-host $OPENSHIFT_VERTX_IP"
-
-  #Add shared conf into classpath.
-  export CLASSPATH=$OPENSHIFT_VERTX_DIR/conf
-
-  client_message "PWD $PWD"
-  client_message "OPTS $VERTX_OPTS"
-  client_message "cluster $vertx_cluster"
-  client_message "ARGS $RUN_ARGS"
-
-  nohup java $VERTX_OPTS -jar $OPENSHIFT_REPO_DIR/application/*.jar $vertx_cluster $RUN_ARGS > $LOG 2>&1 &
-  echo $! > $RUNNING_PID
-}
-
-function stop {
-  client_message "Stopping Vert.x application"
-  if isrunning; then
-    kill `cat $RUNNING_PID`
-    rm $RUNNING_PID
+    vertx_cluster="-cluster -cluster-port $OPENSHIFT_VERTX_CLUSTER_PORT -cluster-host $OPENSHIFT_VERTX_IP"
   fi
+
+  # Start up vertx
+  pushd $OPENSHIFT_REPO_DIR > /dev/null
+
+    export CLASSPATH=$OPENSHIFT_VERTX_DIR/conf
+    export VERTX_JUL_CONFIG=$OPENSHIFT_VERTX_DIR/conf/logging.properties
+    client_message "PWD $PWD"
+    client_message "OPTS $VERTX_OPTS"
+    client_message "cluster $vertx_cluster"
+    client_message "ARGS $RUN_ARGS"
+
+    nohup java $VERTX_OPTS -jar $OPENSHIFT_REPO_DIR/application/*.jar $vertx_cluster $RUN_ARGS > $LOG 2>&1 &
+    echo $! > $RUNNING_PID
+
+    PROCESS_ID=$!
+    echo "$PROCESS_ID" > ${VERTX_PID_FILE}
+  popd > /dev/null
 }
 
-# function setup_hazelcast {
-#   if [ -z ${OPENSHIFT_VERTX_HAZELCAST_CLUSTER:-} ]; then
-#     OPENSHIFT_VERTX_HAZELCAST_CLUSTER="${OPENSHIFT_VERTX_IP}:${OPENSHIFT_VERTX_HAZELCAST_PORT}"
-#   fi
-#
-#   OPENSHIFT_VERTX_PROXY_IP=$(ping -c 1 ${OPENSHIFT_GEAR_DNS} | awk '{ print $3 ; exit }' | sed 's/(//g' | sed 's/)//g')
-#
-#   pushd $OPENSHIFT_VERTX_DIR > /dev/null
-#       sed -i  -e "s/\${env.OPENSHIFT_VERTX_HAZELCAST_PROXY_PORT}/${OPENSHIFT_VERTX_HAZELCAST_PROXY_PORT}/g" \
-#               -e "s/\${env.OPENSHIFT_VERTX_HAZELCAST_PORT}/${OPENSHIFT_VERTX_HAZELCAST_PORT}/g" \
-#               -e "s/\${env.OPENSHIFT_VERTX_PROXY_IP}/${OPENSHIFT_VERTX_PROXY_IP}/g" \
-#               -e "s/\${env.OPENSHIFT_VERTX_IP}/${OPENSHIFT_VERTX_IP}/g" \
-#               -e "s/\${env.OPENSHIFT_VERTX_HAZELCAST_CLUSTER}/${OPENSHIFT_VERTX_HAZELCAST_CLUSTER}/g" \
-#               ./conf/cluster.xml
-#   popd > /dev/null
-# }
-
-
-function restart {
-  client_result "Restarting Vert.x application"
+function restart() {
+  echo "Restarting Vert.x cartridge"
   stop
   start
 }
@@ -121,22 +158,21 @@ function tidy() {
 }
 
 function threaddump() {
-  echo "Thread dump for Vert.x application"
+  echo "Thread dump for Vert.x $version cartridge"
 
   if ! isrunning; then
     echo "Application is stopped"
     exit 1
-  elif [ -f "$RUNNING_PID" ]; then
-    javapid=$(cat $RUNNING_PID);
+  elif [ -f "$VERTX_PID_FILE" ]; then
+    javapid=$(cat $VERTX_PID_FILE);
     kill -3 $javapid
     client_result "Success"
     client_result "The thread dump file will be available via:"
-    client_result "rhc tail $OPENSHIFT_APP_NAME -g $OPENSHIFT_GEAR_UUID -f $LOG -o '-n 250'"
+    client_result "rhc tail $OPENSHIFT_APP_NAME -g $OPENSHIFT_GEAR_UUID -f $logf -o '-n 250'"
   else
-    echo "Failed to locate Vert.x application PID File"
+    echo "Failed to locate Vert.x PID File"
   fi
 }
-
 
 case "$1" in
   start)        start ;;
@@ -147,5 +183,3 @@ case "$1" in
   threaddump)   threaddump ;;
   *)            exit 0
 esac
-
-exit 0
